# Generated by Django 3.0.3 on 2020-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
