# Generated by Django 3.0.3 on 2020-02-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20200211_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bost_or_roast',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
